import numpy as np

my_array = np.array([10, 12, 14, 16, 20, 25])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)
my_array_string = np.array(["Red", "Green", "Orange"])
print(my_array_string)
print(my_array_string.dtype)
print(my_array_string.dtype.itemsize)
extend_array_string = np.append(my_array_string, "Yellow")
print(extend_array_string)
my_array_date = np.array(["1990-10-04", "1989-05-06", "1990-11-04"])
print(my_array_date)
print(my_array_date.dtype)
print(my_array_date.dtype.itemsize)
my_array_date_convert = my_array_date.astype("M")
print(my_array_date_convert)
print(my_array_date_convert.dtype)
print(my_array_date_convert.dtype.itemsize)
